# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=1.21.1
	yarn_mappings=1.21.1+build.3
	loader_version=0.16.14

# Mod Properties
	# modid=ltones
	mod_version = 0.2.4-beta+1.21.1
	maven_group = net.leafenzo
	archives_base_name = ltones

# Dependencies
	fabric_version=0.116.0+1.21.1
	emi_version=1.1.22+1.21.1+fabric
	appleskin_version=3.0.6+mc1.21
	modmenu_version=11.0.3
	axiom_version=rRNZPehD

# JDA
	jda_version=5.0.0-beta.5

# jdk-17.0.5.8-hotspot
