package net.leafenzo.ltones.sound;

import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.sound.SoundEvents;

public class ModBlockSoundGroup {
    public static final BlockSoundGroup AGON = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_AGON_BREAK, ModSoundEvents.BLOCK_AGON_STEP, ModSoundEvents.BLOCK_AGON_PLACE, ModSoundEvents.BLOCK_AGON_HIT, ModSoundEvents.BLOCK_AGON_FALL);
    public static final BlockSoundGroup KORP = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_KORP_BREAK, ModSoundEvents.BLOCK_KORP_STEP, ModSoundEvents.BLOCK_KORP_PLACE, ModSoundEvents.BLOCK_KORP_HIT, ModSoundEvents.BLOCK_KORP_FALL);
    public static final BlockSoundGroup KORP_NODE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_KORP_NODE_BREAK, ModSoundEvents.BLOCK_KORP_STEP, ModSoundEvents.BLOCK_KORP_NODE_PLACE, ModSoundEvents.BLOCK_KORP_HIT, ModSoundEvents.BLOCK_KORP_FALL);
    public static final BlockSoundGroup HOST = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_HOST_BREAK, ModSoundEvents.BLOCK_HOST_STEP, ModSoundEvents.BLOCK_HOST_PLACE, ModSoundEvents.BLOCK_HOST_HIT, ModSoundEvents.BLOCK_HOST_FALL);
    public static final BlockSoundGroup TANK = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_TANK_BREAK, ModSoundEvents.BLOCK_TANK_STEP, ModSoundEvents.BLOCK_TANK_PLACE, ModSoundEvents.BLOCK_TANK_HIT, ModSoundEvents.BLOCK_TANK_FALL);
    public static final BlockSoundGroup NURR = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_NURR_BREAK, ModSoundEvents.BLOCK_NURR_STEP, ModSoundEvents.BLOCK_NURR_PLACE, ModSoundEvents.BLOCK_NURR_HIT, ModSoundEvents.BLOCK_NURR_FALL);
    public static final BlockSoundGroup CRAY = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_CRAY_BREAK, ModSoundEvents.BLOCK_CRAY_STEP, ModSoundEvents.BLOCK_CRAY_PLACE, ModSoundEvents.BLOCK_CRAY_HIT, ModSoundEvents.BLOCK_CRAY_FALL);
    public static final BlockSoundGroup ZANE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_ZANE_BREAK, ModSoundEvents.BLOCK_ZANE_STEP, ModSoundEvents.BLOCK_ZANE_PLACE, ModSoundEvents.BLOCK_ZANE_HIT, ModSoundEvents.BLOCK_ZANE_FALL);
    public static final BlockSoundGroup LAVE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_LAVE_BREAK, ModSoundEvents.BLOCK_LAVE_STEP, ModSoundEvents.BLOCK_LAVE_PLACE, ModSoundEvents.BLOCK_LAVE_HIT, ModSoundEvents.BLOCK_LAVE_FALL);
    public static final BlockSoundGroup VEELD = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_VEELD_BREAK, ModSoundEvents.BLOCK_VEELD_STEP, ModSoundEvents.BLOCK_VEELD_PLACE, ModSoundEvents.BLOCK_VEELD_HIT, ModSoundEvents.BLOCK_VEELD_FALL);
    public static final BlockSoundGroup VEELD_BRICKS = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_VEELD_BRICKS_BREAK, ModSoundEvents.BLOCK_VEELD_BRICKS_STEP, ModSoundEvents.BLOCK_VEELD_BRICKS_PLACE, ModSoundEvents.BLOCK_VEELD_BRICKS_HIT, ModSoundEvents.BLOCK_VEELD_BRICKS_FALL);
    public static final BlockSoundGroup BITT = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_BITT_BREAK, ModSoundEvents.BLOCK_BITT_STEP, ModSoundEvents.BLOCK_BITT_PLACE, ModSoundEvents.BLOCK_BITT_HIT, ModSoundEvents.BLOCK_BITT_FALL);
    public static final BlockSoundGroup CAST = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_CAST_BREAK, ModSoundEvents.BLOCK_CAST_STEP, ModSoundEvents.BLOCK_CAST_PLACE, ModSoundEvents.BLOCK_CAST_HIT, ModSoundEvents.BLOCK_CAST_FALL);
    public static final BlockSoundGroup EXRI = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_EXRI_BREAK, ModSoundEvents.BLOCK_EXRI_STEP, ModSoundEvents.BLOCK_EXRI_PLACE, ModSoundEvents.BLOCK_EXRI_HIT, ModSoundEvents.BLOCK_EXRI_FALL);
    public static final BlockSoundGroup TONE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_TONE_BREAK, ModSoundEvents.BLOCK_TONE_STEP, ModSoundEvents.BLOCK_TONE_PLACE, ModSoundEvents.BLOCK_TONE_HIT, ModSoundEvents.BLOCK_TONE_FALL);
    public static final BlockSoundGroup TONE_BRICKS = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_TONE_BRICKS_BREAK, ModSoundEvents.BLOCK_TONE_BRICKS_STEP, ModSoundEvents.BLOCK_TONE_BRICKS_PLACE, ModSoundEvents.BLOCK_TONE_BRICKS_HIT, ModSoundEvents.BLOCK_TONE_BRICKS_FALL);
    public static final BlockSoundGroup ZTONE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_ZTONE_BREAK, ModSoundEvents.BLOCK_ZTONE_STEP, ModSoundEvents.BLOCK_ZTONE_PLACE, ModSoundEvents.BLOCK_ZTONE_HIT, ModSoundEvents.BLOCK_ZTONE_FALL);
    public static final BlockSoundGroup FLEQ = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_FLEQ_BREAK, ModSoundEvents.BLOCK_FLEQ_STEP, ModSoundEvents.BLOCK_FLEQ_PLACE, ModSoundEvents.BLOCK_FLEQ_HIT, ModSoundEvents.BLOCK_FLEQ_FALL);
    public static final BlockSoundGroup ISZM = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_ISZM_BREAK, ModSoundEvents.BLOCK_ISZM_STEP, ModSoundEvents.BLOCK_ISZM_PLACE, ModSoundEvents.BLOCK_ISZM_HIT, ModSoundEvents.BLOCK_ISZM_FALL);
    public static final BlockSoundGroup ROEN = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_ROEN_BREAK, ModSoundEvents.BLOCK_ROEN_STEP, ModSoundEvents.BLOCK_ROEN_PLACE, ModSoundEvents.BLOCK_ROEN_HIT, ModSoundEvents.BLOCK_ROEN_FALL);
    public static final BlockSoundGroup TYEL = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_TYEL_BREAK, ModSoundEvents.BLOCK_TYEL_STEP, ModSoundEvents.BLOCK_TYEL_PLACE, ModSoundEvents.BLOCK_TYEL_HIT, ModSoundEvents.BLOCK_TYEL_FALL);
    public static final BlockSoundGroup GLAXX = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_GLAXX_BREAK, ModSoundEvents.BLOCK_GLAXX_STEP, ModSoundEvents.BLOCK_GLAXX_PLACE, ModSoundEvents.BLOCK_GLAXX_HIT, ModSoundEvents.BLOCK_GLAXX_FALL);
    public static final BlockSoundGroup FORTT = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_FORTT_BREAK, ModSoundEvents.BLOCK_FORTT_STEP, ModSoundEvents.BLOCK_FORTT_PLACE, ModSoundEvents.BLOCK_FORTT_HIT, ModSoundEvents.BLOCK_FORTT_FALL);
    public static final BlockSoundGroup KRYP = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_KRYP_BREAK, ModSoundEvents.BLOCK_KRYP_STEP, ModSoundEvents.BLOCK_KRYP_PLACE, ModSoundEvents.BLOCK_KRYP_HIT, ModSoundEvents.BLOCK_KRYP_FALL);
    public static final BlockSoundGroup KRYP_BASE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_KRYP_BASE_BREAK, ModSoundEvents.BLOCK_KRYP_BASE_STEP, ModSoundEvents.BLOCK_KRYP_BASE_PLACE, ModSoundEvents.BLOCK_KRYP_BASE_HIT, ModSoundEvents.BLOCK_KRYP_BASE_FALL);
    public static final BlockSoundGroup KRYP_NODE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_KRYP_NODE_BREAK, ModSoundEvents.BLOCK_KRYP_STEP, ModSoundEvents.BLOCK_KRYP_NODE_PLACE, ModSoundEvents.BLOCK_KRYP_HIT, ModSoundEvents.BLOCK_KRYP_FALL);
    public static final BlockSoundGroup MINN = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_MINN_BREAK, ModSoundEvents.BLOCK_MINN_STEP, ModSoundEvents.BLOCK_MINN_PLACE, ModSoundEvents.BLOCK_MINN_HIT, ModSoundEvents.BLOCK_MINN_FALL);
    public static final BlockSoundGroup LITHIUM = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_LITHIUM_BREAK, ModSoundEvents.BLOCK_LITHIUM_STEP, ModSoundEvents.BLOCK_LITHIUM_PLACE, ModSoundEvents.BLOCK_LITHIUM_HIT, ModSoundEvents.BLOCK_LITHIUM_FALL);
    public static final BlockSoundGroup LITHIUM_ORE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_LITHIUM_ORE_BREAK, ModSoundEvents.BLOCK_LITHIUM_ORE_STEP, ModSoundEvents.BLOCK_LITHIUM_ORE_PLACE, ModSoundEvents.BLOCK_LITHIUM_ORE_HIT, ModSoundEvents.BLOCK_LITHIUM_ORE_FALL);
    public static final BlockSoundGroup DEEPSLATE_LITHIUM_ORE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DEEPSLATE_LITHIUM_ORE_BREAK, ModSoundEvents.BLOCK_DEEPSLATE_LITHIUM_ORE_STEP, ModSoundEvents.BLOCK_DEEPSLATE_LITHIUM_ORE_PLACE, ModSoundEvents.BLOCK_DEEPSLATE_LITHIUM_ORE_HIT, ModSoundEvents.BLOCK_DEEPSLATE_LITHIUM_ORE_FALL);
    public static final BlockSoundGroup ZKUL = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_ZKUL_BREAK, ModSoundEvents.BLOCK_ZKUL_STEP, ModSoundEvents.BLOCK_ZKUL_PLACE, ModSoundEvents.BLOCK_ZKUL_HIT, ModSoundEvents.BLOCK_ZKUL_FALL);
    public static final BlockSoundGroup VECT = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_VECT_BREAK, ModSoundEvents.BLOCK_VECT_STEP, ModSoundEvents.BLOCK_VECT_PLACE, ModSoundEvents.BLOCK_VECT_HIT, ModSoundEvents.BLOCK_VECT_FALL);
    public static final BlockSoundGroup VECT_FOIL = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_VECT_FOIL_BREAK, ModSoundEvents.BLOCK_VECT_FOIL_STEP, ModSoundEvents.BLOCK_VECT_FOIL_PLACE, ModSoundEvents.BLOCK_VECT_FOIL_HIT, ModSoundEvents.BLOCK_VECT_FOIL_FALL);


    //TODO add sfx files for these
    public static final BlockSoundGroup STATIC = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_STATIC_BREAK, ModSoundEvents.BLOCK_STATIC_STEP, ModSoundEvents.BLOCK_STATIC_PLACE, ModSoundEvents.BLOCK_STATIC_HIT, ModSoundEvents.BLOCK_STATIC_FALL);
    public static final BlockSoundGroup NEON = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_NEON_BREAK, ModSoundEvents.BLOCK_NEON_STEP, ModSoundEvents.BLOCK_NEON_PLACE, ModSoundEvents.BLOCK_NEON_HIT, ModSoundEvents.BLOCK_NEON_FALL);
    public static final BlockSoundGroup POLYGON = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_POLYGON_BREAK, ModSoundEvents.BLOCK_POLYGON_STEP, ModSoundEvents.BLOCK_POLYGON_PLACE, ModSoundEvents.BLOCK_POLYGON_HIT, ModSoundEvents.BLOCK_POLYGON_FALL);
    public static final BlockSoundGroup LAIR = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_LAIR_BREAK, ModSoundEvents.BLOCK_LAIR_STEP, ModSoundEvents.BLOCK_LAIR_PLACE, ModSoundEvents.BLOCK_LAIR_HIT, ModSoundEvents.BLOCK_LAIR_FALL);
    public static final BlockSoundGroup SOL = new BlockSoundGroup(1.0f, 1.0f, SoundEvents.BLOCK_GLASS_BREAK, SoundEvents.BLOCK_GLASS_STEP, SoundEvents.BLOCK_SHROOMLIGHT_PLACE, SoundEvents.BLOCK_GLASS_HIT, SoundEvents.BLOCK_GLASS_FALL);
    public static final BlockSoundGroup DECAL_SLAG = new BlockSoundGroup(1.0f, 1.0f, SoundEvents.BLOCK_STONE_HIT, SoundEvents.BLOCK_STONE_STEP, SoundEvents.BLOCK_STONE_HIT, SoundEvents.BLOCK_STONE_HIT, SoundEvents.BLOCK_STONE_FALL);
    public static final BlockSoundGroup DECAL_MOULDING = new BlockSoundGroup(0.33f, 1.0f, SoundEvents.BLOCK_GRAVEL_BREAK, SoundEvents.BLOCK_SUSPICIOUS_GRAVEL_STEP, SoundEvents.BLOCK_SUSPICIOUS_GRAVEL_PLACE, SoundEvents.BLOCK_GRAVEL_HIT, SoundEvents.BLOCK_SUSPICIOUS_GRAVEL_FALL);
    public static final BlockSoundGroup TIRE = new BlockSoundGroup(0.66f, 2.4f, SoundEvents.BLOCK_FROGLIGHT_BREAK, SoundEvents.BLOCK_FROGLIGHT_STEP, SoundEvents.BLOCK_FROGLIGHT_PLACE, SoundEvents.BLOCK_FROGLIGHT_HIT,SoundEvents.BLOCK_FROGLIGHT_FALL);
}
