package net.leafenzo.ltones.sound;

import net.minecraft.block.BlockSetType;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.sound.SoundEvents;

public class ModBlockSetType {
    public static final BlockSetType CAST = new BlockSetType("cast", true, ModBlockSoundGroup.CAST,  ModSoundEvents.BLOCK_CAST_DOOR_CLOSE, ModSoundEvents.BLOCK_CAST_DOOR_OPEN, ModSoundEvents.BLOCK_CAST_TRAPDOOR_CLOSE, ModSoundEvents.BLOCK_CAST_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType CRAY = new BlockSetType("cray", true, ModBlockSoundGroup.CRAY,  ModSoundEvents.BLOCK_CRAY_DOOR_CLOSE, ModSoundEvents.BLOCK_CRAY_DOOR_OPEN, ModSoundEvents.BLOCK_CRAY_TRAPDOOR_CLOSE, ModSoundEvents.BLOCK_CRAY_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType TANK = new BlockSetType("tank", true, ModBlockSoundGroup.TANK,  ModSoundEvents.BLOCK_TANK_DOOR_CLOSE, ModSoundEvents.BLOCK_TANK_DOOR_OPEN, ModSoundEvents.BLOCK_TANK_TRAPDOOR_CLOSE, ModSoundEvents.BLOCK_TANK_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType KORP = new BlockSetType("korp", true, ModBlockSoundGroup.KORP,  ModSoundEvents.BLOCK_KORP_DOOR_CLOSE, ModSoundEvents.BLOCK_KORP_DOOR_OPEN, ModSoundEvents.BLOCK_KORP_TRAPDOOR_CLOSE, ModSoundEvents.BLOCK_KORP_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType LAVE = new BlockSetType("lave", true, ModBlockSoundGroup.LAVE,  ModSoundEvents.BLOCK_LAVE_DOOR_CLOSE, ModSoundEvents.BLOCK_LAVE_DOOR_OPEN, ModSoundEvents.BLOCK_LAVE_TRAPDOOR_CLOSE, ModSoundEvents.BLOCK_LAVE_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType VECT = new BlockSetType("vect", true, ModBlockSoundGroup.VECT,  ModSoundEvents.BLOCK_VECT_DOOR_CLOSE, ModSoundEvents.BLOCK_VECT_DOOR_OPEN, ModSoundEvents.BLOCK_VECT_TRAPDOOR_CLOSE, ModSoundEvents.BLOCK_VECT_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType NURR = new BlockSetType("nurr", true, ModBlockSoundGroup.NURR,  ModSoundEvents.BLOCK_NURR_DOOR_CLOSE, ModSoundEvents.BLOCK_NURR_DOOR_OPEN, ModSoundEvents.BLOCK_NURR_TRAPDOOR_CLOSE, ModSoundEvents.BLOCK_NURR_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType LITHIUM = new BlockSetType("lithium", true, ModBlockSoundGroup.LITHIUM,  ModSoundEvents.BLOCK_LITHIUM_DOOR_CLOSE, ModSoundEvents.BLOCK_LITHIUM_DOOR_OPEN, ModSoundEvents.BLOCK_LITHIUM_TRAPDOOR_CLOSE, ModSoundEvents.BLOCK_LITHIUM_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType VEELD = new BlockSetType("veeld", true, ModBlockSoundGroup.VEELD,  ModSoundEvents.BLOCK_VEELD_DOOR_CLOSE, ModSoundEvents.BLOCK_VEELD_DOOR_OPEN, ModSoundEvents.BLOCK_VEELD_TRAPDOOR_CLOSE, ModSoundEvents.BLOCK_VEELD_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType MINN = new BlockSetType("minn", true, ModBlockSoundGroup.MINN,  ModSoundEvents.BLOCK_MINN_DOOR_CLOSE, ModSoundEvents.BLOCK_MINN_DOOR_OPEN, ModSoundEvents.BLOCK_MINN_TRAPDOOR_CLOSE, ModSoundEvents.BLOCK_MINN_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType LAIR = new BlockSetType("lair", true, ModBlockSoundGroup.LAIR,  ModSoundEvents.BLOCK_LAIR_DOOR_CLOSE, ModSoundEvents.BLOCK_LAIR_DOOR_OPEN, ModSoundEvents.BLOCK_LAIR_TRAPDOOR_CLOSE, ModSoundEvents.BLOCK_LAIR_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType KRYP = new BlockSetType("kryp", true, ModBlockSoundGroup.KRYP_BASE,  ModSoundEvents.BLOCK_KRYP_DOOR_CLOSE, ModSoundEvents.BLOCK_KRYP_DOOR_OPEN, ModSoundEvents.BLOCK_KRYP_TRAPDOOR_CLOSE, ModSoundEvents.BLOCK_KRYP_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType EXRI = new BlockSetType("exri", true, ModBlockSoundGroup.EXRI,  ModSoundEvents.BLOCK_EXRI_DOOR_CLOSE, ModSoundEvents.BLOCK_EXRI_DOOR_OPEN, ModSoundEvents.BLOCK_EXRI_TRAPDOOR_CLOSE, ModSoundEvents.BLOCK_EXRI_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType ROEN = new BlockSetType("roen", true, ModBlockSoundGroup.ROEN,  ModSoundEvents.BLOCK_ROEN_DOOR_CLOSE, ModSoundEvents.BLOCK_ROEN_DOOR_OPEN, ModSoundEvents.BLOCK_ROEN_TRAPDOOR_CLOSE, ModSoundEvents.BLOCK_ROEN_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType TONE = new BlockSetType("tone", true, ModBlockSoundGroup.TONE,  ModSoundEvents.BLOCK_TONE_DOOR_CLOSE, ModSoundEvents.BLOCK_TONE_DOOR_OPEN, ModSoundEvents.BLOCK_TONE_TRAPDOOR_CLOSE, ModSoundEvents.BLOCK_TONE_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType FORTT = new BlockSetType("fortt", true, ModBlockSoundGroup.FORTT,  ModSoundEvents.BLOCK_FORTT_DOOR_CLOSE, ModSoundEvents.BLOCK_FORTT_DOOR_OPEN, ModSoundEvents.BLOCK_FORTT_TRAPDOOR_CLOSE, ModSoundEvents.BLOCK_FORTT_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
}
