package net.leafenzo.ltones.sound;

import net.minecraft.sound.BlockSoundGroup;

public class ModBlockSoundGroup {
    public static final BlockSoundGroup DECAL_AMALGAM = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_AMALGAM_BREAK, ModSoundEvents.BLOCK_DECAL_AMALGAM_STEP, ModSoundEvents.BLOCK_DECAL_AMALGAM_PLACE, ModSoundEvents.BLOCK_DECAL_AMALGAM_HIT, ModSoundEvents.BLOCK_DECAL_AMALGAM_FALL);
    public static final BlockSoundGroup DECAL_ANTIBRASS = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_ANTIBRASS_BREAK, ModSoundEvents.BLOCK_DECAL_ANTIBRASS_STEP, ModSoundEvents.BLOCK_DECAL_ANTIBRASS_PLACE, ModSoundEvents.BLOCK_DECAL_ANTIBRASS_HIT, ModSoundEvents.BLOCK_DECAL_ANTIBRASS_FALL);
    public static final BlockSoundGroup DECAL_AZURE_RIVET = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_AZURE_RIVET_BREAK, ModSoundEvents.BLOCK_DECAL_AZURE_RIVET_STEP, ModSoundEvents.BLOCK_DECAL_AZURE_RIVET_PLACE, ModSoundEvents.BLOCK_DECAL_AZURE_RIVET_HIT, ModSoundEvents.BLOCK_DECAL_AZURE_RIVET_FALL);
    public static final BlockSoundGroup DECAL_CONDUCTIUM = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_CONDUCTIUM_BREAK, ModSoundEvents.BLOCK_DECAL_CONDUCTIUM_STEP, ModSoundEvents.BLOCK_DECAL_CONDUCTIUM_PLACE, ModSoundEvents.BLOCK_DECAL_CONDUCTIUM_HIT, ModSoundEvents.BLOCK_DECAL_CONDUCTIUM_FALL);
    public static final BlockSoundGroup DECAL_CORPOREAL_VALOR = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_CORPOREAL_VALOR_BREAK, ModSoundEvents.BLOCK_DECAL_CORPOREAL_VALOR_STEP, ModSoundEvents.BLOCK_DECAL_CORPOREAL_VALOR_PLACE, ModSoundEvents.BLOCK_DECAL_CORPOREAL_VALOR_HIT, ModSoundEvents.BLOCK_DECAL_CORPOREAL_VALOR_FALL);
    public static final BlockSoundGroup DECAL_DIODE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_DIODE_BREAK, ModSoundEvents.BLOCK_DECAL_DIODE_STEP, ModSoundEvents.BLOCK_DECAL_DIODE_PLACE, ModSoundEvents.BLOCK_DECAL_DIODE_HIT, ModSoundEvents.BLOCK_DECAL_DIODE_FALL);
    public static final BlockSoundGroup DECAL_FIBROUS_POWDER = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_FIBROUS_POWDER_BREAK, ModSoundEvents.BLOCK_DECAL_FIBROUS_POWDER_STEP, ModSoundEvents.BLOCK_DECAL_FIBROUS_POWDER_PLACE, ModSoundEvents.BLOCK_DECAL_FIBROUS_POWDER_HIT, ModSoundEvents.BLOCK_DECAL_FIBROUS_POWDER_FALL);
    public static final BlockSoundGroup DECAL_FLAKES = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_FLAKES_BREAK, ModSoundEvents.BLOCK_DECAL_FLAKES_STEP, ModSoundEvents.BLOCK_DECAL_FLAKES_PLACE, ModSoundEvents.BLOCK_DECAL_FLAKES_HIT, ModSoundEvents.BLOCK_DECAL_FLAKES_FALL);
    public static final BlockSoundGroup DECAL_G2V = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_G2V_BREAK, ModSoundEvents.BLOCK_DECAL_G2V_STEP, ModSoundEvents.BLOCK_DECAL_G2V_PLACE, ModSoundEvents.BLOCK_DECAL_G2V_HIT, ModSoundEvents.BLOCK_DECAL_G2V_FALL);
    public static final BlockSoundGroup DECAL_GLASS_TUBE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_GLASS_TUBE_BREAK, ModSoundEvents.BLOCK_DECAL_GLASS_TUBE_STEP, ModSoundEvents.BLOCK_DECAL_GLASS_TUBE_PLACE, ModSoundEvents.BLOCK_DECAL_GLASS_TUBE_HIT, ModSoundEvents.BLOCK_DECAL_GLASS_TUBE_FALL);
    public static final BlockSoundGroup DECAL_GLEAM = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_GLEAM_BREAK, ModSoundEvents.BLOCK_DECAL_GLEAM_STEP, ModSoundEvents.BLOCK_DECAL_GLEAM_PLACE, ModSoundEvents.BLOCK_DECAL_GLEAM_HIT, ModSoundEvents.BLOCK_DECAL_GLEAM_FALL);
    public static final BlockSoundGroup DECAL_JELLY = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_JELLY_BREAK, ModSoundEvents.BLOCK_DECAL_JELLY_STEP, ModSoundEvents.BLOCK_DECAL_JELLY_PLACE, ModSoundEvents.BLOCK_DECAL_JELLY_HIT, ModSoundEvents.BLOCK_DECAL_JELLY_FALL);
    public static final BlockSoundGroup DECAL_KERBESIUM = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_KERBESIUM_BREAK, ModSoundEvents.BLOCK_DECAL_KERBESIUM_STEP, ModSoundEvents.BLOCK_DECAL_KERBESIUM_PLACE, ModSoundEvents.BLOCK_DECAL_KERBESIUM_HIT, ModSoundEvents.BLOCK_DECAL_KERBESIUM_FALL);
    public static final BlockSoundGroup DECAL_LUESIUM = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_LUESIUM_BREAK, ModSoundEvents.BLOCK_DECAL_LUESIUM_STEP, ModSoundEvents.BLOCK_DECAL_LUESIUM_PLACE, ModSoundEvents.BLOCK_DECAL_LUESIUM_HIT, ModSoundEvents.BLOCK_DECAL_LUESIUM_FALL);
    public static final BlockSoundGroup DECAL_MIDASIUM = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_MIDASIUM_BREAK, ModSoundEvents.BLOCK_DECAL_MIDASIUM_STEP, ModSoundEvents.BLOCK_DECAL_MIDASIUM_PLACE, ModSoundEvents.BLOCK_DECAL_MIDASIUM_HIT, ModSoundEvents.BLOCK_DECAL_MIDASIUM_FALL);
    public static final BlockSoundGroup DECAL_MOULDING = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_MOULDING_BREAK, ModSoundEvents.BLOCK_DECAL_MOULDING_STEP, ModSoundEvents.BLOCK_DECAL_MOULDING_PLACE, ModSoundEvents.BLOCK_DECAL_MOULDING_HIT, ModSoundEvents.BLOCK_DECAL_MOULDING_FALL);
    public static final BlockSoundGroup DECAL_NETWORKING = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_NETWORKING_BREAK, ModSoundEvents.BLOCK_DECAL_NETWORKING_STEP, ModSoundEvents.BLOCK_DECAL_NETWORKING_PLACE, ModSoundEvents.BLOCK_DECAL_NETWORKING_HIT, ModSoundEvents.BLOCK_DECAL_NETWORKING_FALL);
    public static final BlockSoundGroup DECAL_OIL = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_OIL_BREAK, ModSoundEvents.BLOCK_DECAL_OIL_STEP, ModSoundEvents.BLOCK_DECAL_OIL_PLACE, ModSoundEvents.BLOCK_DECAL_OIL_HIT, ModSoundEvents.BLOCK_DECAL_OIL_FALL);
    public static final BlockSoundGroup DECAL_ORGANIC_BRASS = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_ORGANIC_BRASS_BREAK, ModSoundEvents.BLOCK_DECAL_ORGANIC_BRASS_STEP, ModSoundEvents.BLOCK_DECAL_ORGANIC_BRASS_PLACE, ModSoundEvents.BLOCK_DECAL_ORGANIC_BRASS_HIT, ModSoundEvents.BLOCK_DECAL_ORGANIC_BRASS_FALL);
    public static final BlockSoundGroup DECAL_PLAQUE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_PLAQUE_BREAK, ModSoundEvents.BLOCK_DECAL_PLAQUE_STEP, ModSoundEvents.BLOCK_DECAL_PLAQUE_PLACE, ModSoundEvents.BLOCK_DECAL_PLAQUE_HIT, ModSoundEvents.BLOCK_DECAL_PLAQUE_FALL);
    public static final BlockSoundGroup DECAL_POLYCARBONATE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_POLYCARBONATE_BREAK, ModSoundEvents.BLOCK_DECAL_POLYCARBONATE_STEP, ModSoundEvents.BLOCK_DECAL_POLYCARBONATE_PLACE, ModSoundEvents.BLOCK_DECAL_POLYCARBONATE_HIT, ModSoundEvents.BLOCK_DECAL_POLYCARBONATE_FALL);
    public static final BlockSoundGroup DECAL_POLYMER = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_POLYMER_BREAK, ModSoundEvents.BLOCK_DECAL_POLYMER_STEP, ModSoundEvents.BLOCK_DECAL_POLYMER_PLACE, ModSoundEvents.BLOCK_DECAL_POLYMER_HIT, ModSoundEvents.BLOCK_DECAL_POLYMER_FALL);
    public static final BlockSoundGroup DECAL_REBITH = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_REBITH_BREAK, ModSoundEvents.BLOCK_DECAL_REBITH_STEP, ModSoundEvents.BLOCK_DECAL_REBITH_PLACE, ModSoundEvents.BLOCK_DECAL_REBITH_HIT, ModSoundEvents.BLOCK_DECAL_REBITH_FALL);
    public static final BlockSoundGroup DECAL_SCARLET_MEMBRANE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_SCARLET_MEMBRANE_BREAK, ModSoundEvents.BLOCK_DECAL_SCARLET_MEMBRANE_STEP, ModSoundEvents.BLOCK_DECAL_SCARLET_MEMBRANE_PLACE, ModSoundEvents.BLOCK_DECAL_SCARLET_MEMBRANE_HIT, ModSoundEvents.BLOCK_DECAL_SCARLET_MEMBRANE_FALL);
    public static final BlockSoundGroup DECAL_SCREEN = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_SCREEN_BREAK, ModSoundEvents.BLOCK_DECAL_SCREEN_STEP, ModSoundEvents.BLOCK_DECAL_SCREEN_PLACE, ModSoundEvents.BLOCK_DECAL_SCREEN_HIT, ModSoundEvents.BLOCK_DECAL_SCREEN_FALL);
    public static final BlockSoundGroup DECAL_SHADE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_SHADE_BREAK, ModSoundEvents.BLOCK_DECAL_SHADE_STEP, ModSoundEvents.BLOCK_DECAL_SHADE_PLACE, ModSoundEvents.BLOCK_DECAL_SHADE_HIT, ModSoundEvents.BLOCK_DECAL_SHADE_FALL);
    public static final BlockSoundGroup DECAL_SHEETING = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_SHEETING_BREAK, ModSoundEvents.BLOCK_DECAL_SHEETING_STEP, ModSoundEvents.BLOCK_DECAL_SHEETING_PLACE, ModSoundEvents.BLOCK_DECAL_SHEETING_HIT, ModSoundEvents.BLOCK_DECAL_SHEETING_FALL);
    public static final BlockSoundGroup DECAL_SLAG = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_SLAG_BREAK, ModSoundEvents.BLOCK_DECAL_SLAG_STEP, ModSoundEvents.BLOCK_DECAL_SLAG_PLACE, ModSoundEvents.BLOCK_DECAL_SLAG_HIT, ModSoundEvents.BLOCK_DECAL_SLAG_FALL);
    public static final BlockSoundGroup DECAL_SLUMP = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_SLUMP_BREAK, ModSoundEvents.BLOCK_DECAL_SLUMP_STEP, ModSoundEvents.BLOCK_DECAL_SLUMP_PLACE, ModSoundEvents.BLOCK_DECAL_SLUMP_HIT, ModSoundEvents.BLOCK_DECAL_SLUMP_FALL);
    public static final BlockSoundGroup DECAL_TAWSINE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_TAWSINE_BREAK, ModSoundEvents.BLOCK_DECAL_TAWSINE_STEP, ModSoundEvents.BLOCK_DECAL_TAWSINE_PLACE, ModSoundEvents.BLOCK_DECAL_TAWSINE_HIT, ModSoundEvents.BLOCK_DECAL_TAWSINE_FALL);
    public static final BlockSoundGroup DECAL_THINKING_METAL = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DECAL_THINKING_METAL_BREAK, ModSoundEvents.BLOCK_DECAL_THINKING_METAL_STEP, ModSoundEvents.BLOCK_DECAL_THINKING_METAL_PLACE, ModSoundEvents.BLOCK_DECAL_THINKING_METAL_HIT, ModSoundEvents.BLOCK_DECAL_THINKING_METAL_FALL);

    public static final BlockSoundGroup ANTENNA = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_ANTENNA_BREAK, ModSoundEvents.BLOCK_ANTENNA_STEP, ModSoundEvents.BLOCK_ANTENNA_PLACE, ModSoundEvents.BLOCK_ANTENNA_HIT, ModSoundEvents.BLOCK_ANTENNA_FALL);
    public static final BlockSoundGroup RADIO = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_RADIO_BREAK, ModSoundEvents.BLOCK_RADIO_STEP, ModSoundEvents.BLOCK_RADIO_PLACE, ModSoundEvents.BLOCK_RADIO_HIT, ModSoundEvents.BLOCK_RADIO_FALL);

    public static final BlockSoundGroup APPLIANCE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_APPLIANCE_BREAK, ModSoundEvents.BLOCK_APPLIANCE_STEP, ModSoundEvents.BLOCK_APPLIANCE_PLACE, ModSoundEvents.BLOCK_APPLIANCE_HIT, ModSoundEvents.BLOCK_APPLIANCE_FALL);
    public static final BlockSoundGroup CRT = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_CRT_BREAK, ModSoundEvents.BLOCK_CRT_STEP, ModSoundEvents.BLOCK_CRT_PLACE, ModSoundEvents.BLOCK_CRT_HIT, ModSoundEvents.BLOCK_CRT_FALL);

    public static final BlockSoundGroup AGON = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_AGON_BREAK, ModSoundEvents.BLOCK_AGON_STEP, ModSoundEvents.BLOCK_AGON_PLACE, ModSoundEvents.BLOCK_AGON_HIT, ModSoundEvents.BLOCK_AGON_FALL);
    public static final BlockSoundGroup JELT = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_JELT_BREAK, ModSoundEvents.BLOCK_JELT_STEP, ModSoundEvents.BLOCK_JELT_PLACE, ModSoundEvents.BLOCK_JELT_HIT, ModSoundEvents.BLOCK_JELT_FALL);
    public static final BlockSoundGroup AZUR = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_AZUR_BREAK, ModSoundEvents.BLOCK_AZUR_STEP, ModSoundEvents.BLOCK_AZUR_PLACE, ModSoundEvents.BLOCK_AZUR_HIT, ModSoundEvents.BLOCK_AZUR_FALL);
    public static final BlockSoundGroup KORP = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_KORP_BREAK, ModSoundEvents.BLOCK_KORP_STEP, ModSoundEvents.BLOCK_KORP_PLACE, ModSoundEvents.BLOCK_KORP_HIT, ModSoundEvents.BLOCK_KORP_FALL);
    public static final BlockSoundGroup KORP_NODE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_KORP_NODE_BREAK, ModSoundEvents.BLOCK_KORP_STEP, ModSoundEvents.BLOCK_KORP_NODE_PLACE, ModSoundEvents.BLOCK_KORP_HIT, ModSoundEvents.BLOCK_KORP_FALL);
    public static final BlockSoundGroup HOST = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_HOST_BREAK, ModSoundEvents.BLOCK_HOST_STEP, ModSoundEvents.BLOCK_HOST_PLACE, ModSoundEvents.BLOCK_HOST_HIT, ModSoundEvents.BLOCK_HOST_FALL);
    public static final BlockSoundGroup TANK = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_TANK_BREAK, ModSoundEvents.BLOCK_TANK_STEP, ModSoundEvents.BLOCK_TANK_PLACE, ModSoundEvents.BLOCK_TANK_HIT, ModSoundEvents.BLOCK_TANK_FALL);
    public static final BlockSoundGroup NURR = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_NURR_BREAK, ModSoundEvents.BLOCK_NURR_STEP, ModSoundEvents.BLOCK_NURR_PLACE, ModSoundEvents.BLOCK_NURR_HIT, ModSoundEvents.BLOCK_NURR_FALL);
    public static final BlockSoundGroup CRAY = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_CRAY_BREAK, ModSoundEvents.BLOCK_CRAY_STEP, ModSoundEvents.BLOCK_CRAY_PLACE, ModSoundEvents.BLOCK_CRAY_HIT, ModSoundEvents.BLOCK_CRAY_FALL);
    public static final BlockSoundGroup ZANE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_ZANE_BREAK, ModSoundEvents.BLOCK_ZANE_STEP, ModSoundEvents.BLOCK_ZANE_PLACE, ModSoundEvents.BLOCK_ZANE_HIT, ModSoundEvents.BLOCK_ZANE_FALL);
    public static final BlockSoundGroup LAVE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_LAVE_BREAK, ModSoundEvents.BLOCK_LAVE_STEP, ModSoundEvents.BLOCK_LAVE_PLACE, ModSoundEvents.BLOCK_LAVE_HIT, ModSoundEvents.BLOCK_LAVE_FALL);
    public static final BlockSoundGroup VEELD = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_VEELD_BREAK, ModSoundEvents.BLOCK_VEELD_STEP, ModSoundEvents.BLOCK_VEELD_PLACE, ModSoundEvents.BLOCK_VEELD_HIT, ModSoundEvents.BLOCK_VEELD_FALL);
    public static final BlockSoundGroup VEELD_BRICKS = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_VEELD_BRICKS_BREAK, ModSoundEvents.BLOCK_VEELD_BRICKS_STEP, ModSoundEvents.BLOCK_VEELD_BRICKS_PLACE, ModSoundEvents.BLOCK_VEELD_BRICKS_HIT, ModSoundEvents.BLOCK_VEELD_BRICKS_FALL);
    public static final BlockSoundGroup REDDS = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_REDDS_BREAK, ModSoundEvents.BLOCK_REDDS_STEP, ModSoundEvents.BLOCK_REDDS_PLACE, ModSoundEvents.BLOCK_REDDS_HIT, ModSoundEvents.BLOCK_REDDS_FALL);
    public static final BlockSoundGroup BITT = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_BITT_BREAK, ModSoundEvents.BLOCK_BITT_STEP, ModSoundEvents.BLOCK_BITT_PLACE, ModSoundEvents.BLOCK_BITT_HIT, ModSoundEvents.BLOCK_BITT_FALL);
    public static final BlockSoundGroup CAST = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_CAST_BREAK, ModSoundEvents.BLOCK_CAST_STEP, ModSoundEvents.BLOCK_CAST_PLACE, ModSoundEvents.BLOCK_CAST_HIT, ModSoundEvents.BLOCK_CAST_FALL);
    public static final BlockSoundGroup EXRI = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_EXRI_BREAK, ModSoundEvents.BLOCK_EXRI_STEP, ModSoundEvents.BLOCK_EXRI_PLACE, ModSoundEvents.BLOCK_EXRI_HIT, ModSoundEvents.BLOCK_EXRI_FALL);
    public static final BlockSoundGroup TONE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_TONE_BREAK, ModSoundEvents.BLOCK_TONE_STEP, ModSoundEvents.BLOCK_TONE_PLACE, ModSoundEvents.BLOCK_TONE_HIT, ModSoundEvents.BLOCK_TONE_FALL);
    public static final BlockSoundGroup TONE_BRICKS = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_TONE_BRICKS_BREAK, ModSoundEvents.BLOCK_TONE_BRICKS_STEP, ModSoundEvents.BLOCK_TONE_BRICKS_PLACE, ModSoundEvents.BLOCK_TONE_BRICKS_HIT, ModSoundEvents.BLOCK_TONE_BRICKS_FALL);
    public static final BlockSoundGroup ZTONE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_ZTONE_BREAK, ModSoundEvents.BLOCK_ZTONE_STEP, ModSoundEvents.BLOCK_ZTONE_PLACE, ModSoundEvents.BLOCK_ZTONE_HIT, ModSoundEvents.BLOCK_ZTONE_FALL);
    public static final BlockSoundGroup FLEQ = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_FLEQ_BREAK, ModSoundEvents.BLOCK_FLEQ_STEP, ModSoundEvents.BLOCK_FLEQ_PLACE, ModSoundEvents.BLOCK_FLEQ_HIT, ModSoundEvents.BLOCK_FLEQ_FALL);
    public static final BlockSoundGroup ISZM = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_ISZM_BREAK, ModSoundEvents.BLOCK_ISZM_STEP, ModSoundEvents.BLOCK_ISZM_PLACE, ModSoundEvents.BLOCK_ISZM_HIT, ModSoundEvents.BLOCK_ISZM_FALL);
    public static final BlockSoundGroup ROEN = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_ROEN_BREAK, ModSoundEvents.BLOCK_ROEN_STEP, ModSoundEvents.BLOCK_ROEN_PLACE, ModSoundEvents.BLOCK_ROEN_HIT, ModSoundEvents.BLOCK_ROEN_FALL);
    public static final BlockSoundGroup ROST = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_ROST_BREAK, ModSoundEvents.BLOCK_ROST_STEP, ModSoundEvents.BLOCK_ROST_PLACE, ModSoundEvents.BLOCK_ROST_HIT, ModSoundEvents.BLOCK_ROST_FALL);
    public static final BlockSoundGroup ROST_RUST = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_ROST_RUST_BREAK, ModSoundEvents.BLOCK_ROST_RUST_STEP, ModSoundEvents.BLOCK_ROST_RUST_PLACE, ModSoundEvents.BLOCK_ROST_RUST_HIT, ModSoundEvents.BLOCK_ROST_RUST_FALL);
    public static final BlockSoundGroup TYEL = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_TYEL_BREAK, ModSoundEvents.BLOCK_TYEL_STEP, ModSoundEvents.BLOCK_TYEL_PLACE, ModSoundEvents.BLOCK_TYEL_HIT, ModSoundEvents.BLOCK_TYEL_FALL);
    public static final BlockSoundGroup GLAXX = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_GLAXX_BREAK, ModSoundEvents.BLOCK_GLAXX_STEP, ModSoundEvents.BLOCK_GLAXX_PLACE, ModSoundEvents.BLOCK_GLAXX_HIT, ModSoundEvents.BLOCK_GLAXX_FALL);
    public static final BlockSoundGroup FORTT = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_FORTT_BREAK, ModSoundEvents.BLOCK_FORTT_STEP, ModSoundEvents.BLOCK_FORTT_PLACE, ModSoundEvents.BLOCK_FORTT_HIT, ModSoundEvents.BLOCK_FORTT_FALL);
    public static final BlockSoundGroup KRYP = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_KRYP_BREAK, ModSoundEvents.BLOCK_KRYP_STEP, ModSoundEvents.BLOCK_KRYP_PLACE, ModSoundEvents.BLOCK_KRYP_HIT, ModSoundEvents.BLOCK_KRYP_FALL);
    public static final BlockSoundGroup KRYP_BASE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_KRYP_BASE_BREAK, ModSoundEvents.BLOCK_KRYP_BASE_STEP, ModSoundEvents.BLOCK_KRYP_BASE_PLACE, ModSoundEvents.BLOCK_KRYP_BASE_HIT, ModSoundEvents.BLOCK_KRYP_BASE_FALL);
    public static final BlockSoundGroup KRYP_NODE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_KRYP_NODE_BREAK, ModSoundEvents.BLOCK_KRYP_STEP, ModSoundEvents.BLOCK_KRYP_NODE_PLACE, ModSoundEvents.BLOCK_KRYP_HIT, ModSoundEvents.BLOCK_KRYP_FALL);
    public static final BlockSoundGroup MINN = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_MINN_BREAK, ModSoundEvents.BLOCK_MINN_STEP, ModSoundEvents.BLOCK_MINN_PLACE, ModSoundEvents.BLOCK_MINN_HIT, ModSoundEvents.BLOCK_MINN_FALL);
    public static final BlockSoundGroup LUESIUM = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_LUESIUM_BREAK, ModSoundEvents.BLOCK_LUESIUM_STEP, ModSoundEvents.BLOCK_LUESIUM_PLACE, ModSoundEvents.BLOCK_LUESIUM_HIT, ModSoundEvents.BLOCK_LUESIUM_FALL);
    public static final BlockSoundGroup LUESIUM_ORE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_LUESIUM_ORE_BREAK, ModSoundEvents.BLOCK_LUESIUM_ORE_STEP, ModSoundEvents.BLOCK_LUESIUM_ORE_PLACE, ModSoundEvents.BLOCK_LUESIUM_ORE_HIT, ModSoundEvents.BLOCK_LUESIUM_ORE_FALL);
    public static final BlockSoundGroup DEEPSLATE_LUESIUM_ORE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_DEEPSLATE_LUESIUM_ORE_BREAK, ModSoundEvents.BLOCK_DEEPSLATE_LUESIUM_ORE_STEP, ModSoundEvents.BLOCK_DEEPSLATE_LUESIUM_ORE_PLACE, ModSoundEvents.BLOCK_DEEPSLATE_LUESIUM_ORE_HIT, ModSoundEvents.BLOCK_DEEPSLATE_LUESIUM_ORE_FALL);
    public static final BlockSoundGroup ANTIBRASS = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_ANTIBRASS_BREAK, ModSoundEvents.BLOCK_ANTIBRASS_STEP, ModSoundEvents.BLOCK_ANTIBRASS_PLACE, ModSoundEvents.BLOCK_ANTIBRASS_HIT, ModSoundEvents.BLOCK_ANTIBRASS_FALL);
    public static final BlockSoundGroup MYST = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_MYST_BREAK, ModSoundEvents.BLOCK_MYST_STEP, ModSoundEvents.BLOCK_MYST_PLACE, ModSoundEvents.BLOCK_MYST_HIT, ModSoundEvents.BLOCK_MYST_FALL);
    public static final BlockSoundGroup VECT = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_VECT_BREAK, ModSoundEvents.BLOCK_VECT_STEP, ModSoundEvents.BLOCK_VECT_PLACE, ModSoundEvents.BLOCK_VECT_HIT, ModSoundEvents.BLOCK_VECT_FALL);
    public static final BlockSoundGroup VECT_FOIL = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_VECT_FOIL_BREAK, ModSoundEvents.BLOCK_VECT_FOIL_STEP, ModSoundEvents.BLOCK_VECT_FOIL_PLACE, ModSoundEvents.BLOCK_VECT_FOIL_HIT, ModSoundEvents.BLOCK_VECT_FOIL_FALL);
    public static final BlockSoundGroup LAIR = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_LAIR_BREAK, ModSoundEvents.BLOCK_LAIR_STEP, ModSoundEvents.BLOCK_LAIR_PLACE, ModSoundEvents.BLOCK_LAIR_HIT, ModSoundEvents.BLOCK_LAIR_FALL);
    public static final BlockSoundGroup SOL = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_SOL_BREAK, ModSoundEvents.BLOCK_SOL_STEP, ModSoundEvents.BLOCK_SOL_PLACE, ModSoundEvents.BLOCK_SOL_HIT, ModSoundEvents.BLOCK_SOL_FALL);
    public static final BlockSoundGroup SYNC = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_SYNC_BREAK, ModSoundEvents.BLOCK_SYNC_STEP, ModSoundEvents.BLOCK_SYNC_PLACE, ModSoundEvents.BLOCK_SYNC_HIT, ModSoundEvents.BLOCK_SYNC_FALL);
    public static final BlockSoundGroup TIRE = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_TIRE_BREAK, ModSoundEvents.BLOCK_TIRE_STEP, ModSoundEvents.BLOCK_TIRE_PLACE, ModSoundEvents.BLOCK_TIRE_HIT, ModSoundEvents.BLOCK_TIRE_FALL);

    public static final BlockSoundGroup ZKUL = new BlockSoundGroup(1.0f, 1.0f, ModSoundEvents.BLOCK_ZKUL_BREAK, ModSoundEvents.BLOCK_ZKUL_STEP, ModSoundEvents.BLOCK_ZKUL_PLACE, ModSoundEvents.BLOCK_ZKUL_HIT, ModSoundEvents.BLOCK_ZKUL_FALL);
}
