package net.leafenzo.ltones.sound;

import net.minecraft.block.BlockSetType;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.sound.SoundEvents;

public class ModBlockSetType {
    public static final BlockSetType CAST = new BlockSetType("cast", true, ModBlockSoundGroup.CAST,  ModSoundEvents.BLOCK_CAST_DOOR_CLOSE, ModSoundEvents.BLOCK_CAST_DOOR_OPEN, SoundEvents.BLOCK_IRON_TRAPDOOR_CLOSE, SoundEvents.BLOCK_IRON_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType MINN = new BlockSetType("minn", true, ModBlockSoundGroup.MINN,  ModSoundEvents.BLOCK_MINN_DOOR_CLOSE, ModSoundEvents.BLOCK_MINN_DOOR_OPEN, SoundEvents.BLOCK_IRON_TRAPDOOR_CLOSE, SoundEvents.BLOCK_IRON_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType LAIR = new BlockSetType("lair", true, ModBlockSoundGroup.LAIR,  ModSoundEvents.BLOCK_LAIR_DOOR_CLOSE, ModSoundEvents.BLOCK_LAIR_DOOR_OPEN, SoundEvents.BLOCK_IRON_TRAPDOOR_CLOSE, SoundEvents.BLOCK_IRON_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType KRYP = new BlockSetType("kryp", true, ModBlockSoundGroup.KRYP_BASE,  ModSoundEvents.BLOCK_KRYP_DOOR_CLOSE, ModSoundEvents.BLOCK_KRYP_DOOR_OPEN, SoundEvents.BLOCK_IRON_TRAPDOOR_CLOSE, SoundEvents.BLOCK_IRON_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType EXRI = new BlockSetType("exri", true, ModBlockSoundGroup.EXRI,  ModSoundEvents.BLOCK_EXRI_DOOR_CLOSE, ModSoundEvents.BLOCK_EXRI_DOOR_OPEN, SoundEvents.BLOCK_IRON_TRAPDOOR_CLOSE, SoundEvents.BLOCK_IRON_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType ROEN = new BlockSetType("roen", true, ModBlockSoundGroup.ROEN,  ModSoundEvents.BLOCK_ROEN_DOOR_CLOSE, ModSoundEvents.BLOCK_ROEN_DOOR_OPEN, SoundEvents.BLOCK_IRON_TRAPDOOR_CLOSE, SoundEvents.BLOCK_IRON_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
    public static final BlockSetType TONE = new BlockSetType("tone", true, ModBlockSoundGroup.TONE,  ModSoundEvents.BLOCK_TONE_DOOR_CLOSE, ModSoundEvents.BLOCK_TONE_DOOR_OPEN, SoundEvents.BLOCK_IRON_TRAPDOOR_CLOSE, SoundEvents.BLOCK_IRON_TRAPDOOR_OPEN, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.BLOCK_METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.BLOCK_STONE_BUTTON_CLICK_OFF, SoundEvents.BLOCK_STONE_BUTTON_CLICK_ON);
}
